version: '3.8'

services:
  incredible-squaring-avs:
    build: .
    volumes:
      - .:/app
    working_dir: /app
    environment:
      - PYTHONPATH=/app
    command: make test

  # Optional: service for development
  incredible-squaring-dev:
    build: .
    volumes:
      - .:/app
    working_dir: /app
    environment:
      - PYTHONPATH=/app
    command: bash
    stdin_open: true
    tty: true 